export const COUNTRY_FLAGS: Record<string, string> = {
  "afghanistan": "🇦🇫",
  "albania": "🇦🇱",
  "algeria": "🇩🇿",
  "andorra": "🇦🇩",
  "angola": "🇦🇴",
  "antigua and barbuda": "🇦🇬",
  "argentina": "🇦🇷",
  "armenia": "🇦🇲",
  "australia": "🇦🇺",
  "austria": "🇦🇹",
  "azerbaijan": "🇦🇿",
  "bahamas": "🇧🇸",
  "bahrain": "🇧🇭",
  "bangladesh": "🇧🇩",
  "barbados": "🇧🇧",
  "belarus": "🇧🇾",
  "belgium": "🇧🇪",
  "belize": "🇧🇿",
  "benin": "🇧🇯",
  "bhutan": "🇧🇹",
  "bolivia": "🇧🇴",
  "bosnia and herzegovina": "🇧🇦",
  "bosnia": "🇧🇦",
  "herzegovina": "🇧🇦",
  "botswana": "🇧🇼",
  "brazil": "🇧🇷",
  "brunei": "🇧🇳",
  "bulgaria": "🇧🇬",
  "burkina faso": "🇧🇫",
  "burundi": "🇧🇮",
  "cabo verde": "🇨🇻",
  "cape verde": "🇨🇻",
  "cambodia": "🇰🇭",
  "cameroon": "🇨🇲",
  "canada": "🇨🇦",
  "central african republic": "🇨🇫",
  "chad": "🇹🇩",
  "chile": "🇨🇱",
  "china": "🇨🇳",
  "colombia": "🇨🇴",
  "comoros": "🇰🇲",
  "congo": "🇨🇬",
  "costa rica": "🇨🇷",
  "croatia": "🇭🇷",
  "cuba": "🇨🇺",
  "cyprus": "🇨🇾",
  "czech republic": "🇨🇿",
  "czechia": "🇨🇿",
  "democratic republic of the congo": "🇨🇩",
  "denmark": "🇩🇰",
  "djibouti": "🇩🇯",
  "dominica": "🇩🇲",
  "dominican republic": "🇩🇴",
  "east timor": "🇹🇱",
  "timor leste": "🇹🇱",
  "ecuador": "🇪🇨",
  "egypt": "🇪🇬",
  "el salvador": "🇸🇻",
  "england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "equatorial guinea": "🇬🇶",
  "eritrea": "🇪🇷",
  "estonia": "🇪🇪",
  "eswatini": "🇸🇿",
  "swaziland": "🇸🇿",
  "ethiopia": "🇪🇹",
  "fiji": "🇫🇯",
  "finland": "🇫🇮",
  "france": "🇫🇷",
  "gabon": "🇬🇦",
  "gambia": "🇬🇲",
  "georgia": "🇬🇪",
  "germany": "🇩🇪",
  "ghana": "🇬🇭",
  "greece": "🇬🇷",
  "grenada": "🇬🇩",
  "guatemala": "🇬🇹",
  "guinea": "🇬🇳",
  "guinea bissau": "🇬🇼",
  "guyana": "🇬🇾",
  "haiti": "🇭🇹",
  "honduras": "🇭🇳",
  "hungary": "🇭🇺",
  "iceland": "🇮🇸",
  "india": "🇮🇳",
  "indonesia": "🇮🇩",
  "iran": "🇮🇷",
  "iraq": "🇮🇶",
  "ireland": "🇮🇪",
  "israel": "🇮🇱",
  "italy": "🇮🇹",
  "ivory coast": "🇨🇮",
  "cote d'ivoire": "🇨🇮",
  "jamaica": "🇯🇲",
  "japan": "🇯🇵",
  "jordan": "🇯🇴",
  "kazakhstan": "🇰🇿",
  "kenya": "🇰🇪",
  "kiribati": "🇰🇮",
  "kosovo": "🇽🇰",
  "kuwait": "🇰🇼",
  "kyrgyzstan": "🇰🇬",
  "laos": "🇱🇦",
  "latvia": "🇱🇻",
  "lebanon": "🇱🇧",
  "lesotho": "🇱🇸",
  "liberia": "🇱🇷",
  "libya": "🇱🇾",
  "liechtenstein": "🇱🇮",
  "lithuania": "🇱🇹",
  "luxembourg": "🇱🇺",
  "madagascar": "🇲🇬",
  "malawi": "🇲🇼",
  "malaysia": "🇲🇾",
  "maldives": "🇲🇻",
  "mali": "🇲🇱",
  "malta": "🇲🇹",
  "marshall islands": "🇲🇭",
  "mauritania": "🇲🇷",
  "mauritius": "🇲🇺",
  "mexico": "🇲🇽",
  "micronesia": "🇫🇲",
  "moldova": "🇲🇩",
  "monaco": "🇲🇨",
  "mongolia": "🇲🇳",
  "montenegro": "🇲🇪",
  "morocco": "🇲🇦",
  "mozambique": "🇲🇿",
  "myanmar": "🇲🇲",
  "burma": "🇲🇲",
  "namibia": "🇳🇦",
  "nauru": "🇳🇷",
  "nepal": "🇳🇵",
  "netherlands": "🇳🇱",
  "holland": "🇳🇱",
  "new zealand": "🇳🇿",
  "nicaragua": "🇳🇮",
  "niger": "🇳🇪",
  "nigeria": "🇳🇬",
  "north korea": "🇰🇵",
  "north macedonia": "🇲🇰",
  "macedonia": "🇲🇰",
  "northern ireland": "🇬🇧",
  "norway": "🇳🇴",
  "oman": "🇴🇲",
  "pakistan": "🇵🇰",
  "palau": "🇵🇼",
  "palestine": "🇵🇸",
  "panama": "🇵🇦",
  "papua new guinea": "🇵🇬",
  "paraguay": "🇵🇾",
  "peru": "🇵🇪",
  "philippines": "🇵🇭",
  "poland": "🇵🇱",
  "portugal": "🇵🇹",
  "qatar": "🇶🇦",
  "romania": "🇷🇴",
  "russia": "🇷🇺",
  "rwanda": "🇷🇼",
  "saint kitts and nevis": "🇰🇳",
  "saint lucia": "🇱🇨",
  "saint vincent and the grenadines": "🇻🇨",
  "samoa": "🇼🇸",
  "san marino": "🇸🇲",
  "sao tome and principe": "🇸🇹",
  "saudi arabia": "🇸🇦",
  "scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "senegal": "🇸🇳",
  "serbia": "🇷🇸",
  "seychelles": "🇸🇨",
  "sierra leone": "🇸🇱",
  "singapore": "🇸🇬",
  "slovakia": "🇸🇰",
  "slovenia": "🇸🇮",
  "solomon islands": "🇸🇧",
  "somalia": "🇸🇴",
  "south africa": "🇿🇦",
  "south korea": "🇰🇷",
  "south sudan": "🇸🇸",
  "spain": "🇪🇸",
  "sri lanka": "🇱🇰",
  "sudan": "🇸🇩",
  "suriname": "🇸🇷",
  "sweden": "🇸🇪",
  "switzerland": "🇨🇭",
  "syria": "🇸🇾",
  "taiwan": "🇹🇼",
  "tajikistan": "🇹🇯",
  "tanzania": "🇹🇿",
  "thailand": "🇹🇭",
  "togo": "🇹🇬",
  "tonga": "🇹🇴",
  "trinidad and tobago": "🇹🇹",
  "trinidad": "🇹🇹",
  "tobago": "🇹🇹",
  "tunisia": "🇹🇳",
  "turkey": "🇹🇷",
  "turkmenistan": "🇹🇲",
  "tuvalu": "🇹🇻",
  "uganda": "🇺🇬",
  "ukraine": "🇺🇦",
  "united arab emirates": "🇦🇪",
  "uae": "🇦🇪",
  "united kingdom": "🇬🇧",
  "uk": "🇬🇧",
  "britain": "🇬🇧",
  "great britain": "🇬🇧",
  "united states": "🇺🇸",
  "usa": "🇺🇸",
  "us": "🇺🇸",
  "america": "🇺🇸",
  "uruguay": "🇺🇾",
  "uzbekistan": "🇺🇿",
  "vanuatu": "🇻🇺",
  "vatican city": "🇻🇦",
  "venezuela": "🇻🇪",
  "vietnam": "🇻🇳",
  "wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "yemen": "🇾🇪",
  "zambia": "🇿🇲",
  "zimbabwe": "🇿🇼",
};

export function getFlagEmoji(countryName: string): string {
  if (!countryName) return "";
  const normalized = countryName.toLowerCase().trim();
  return COUNTRY_FLAGS[normalized] || "";
}

export function getAllCountryNames(): string[] {
  return Object.keys(COUNTRY_FLAGS).sort();
}
